var JS_CITIES_DATA = 
[
"----- PERSONAL TIMES -------------------",
"00.000.PERSONAL",

"----- SAUDI ARABIA ---------------------",
"SA.ABGAIG. أبقيق",
"SA.Abha. أبها",
"SA.ِABU-ARISH.    أبوعريش",
"SA.ِADUM.      أضم",
"SA.AFLAJ. أﻷفلاج",
"SA.AHAD-ALMASARRIHA. أحد ألمسارحه",
"SA.ِAHADRUFIDAH.   أحد رفيده",
"SA.AL-AGEEG.  العقيق",
"SA.AL-AHASA. الاحساء",
"SA.ALASHTA.   الاشتاء",
"SA.AL-BAHAH.الباحه",
"SA.ِALBKIRIA.  البكيريه",
"SA.AL-DULAM.الدلم",
"SA.ِAL-KHAFJI.    الخفجي",
"SA.AL-KHARJ.  الخرج",
"SA.AL-KHUBAR.الخبر",
"SA.ِAL-KHURMA.     الخرمه",
"SA.AL-LITH.الليث",
"SA.AL-MADINAH.المدينه المنوره",
"SA.ِAL-MANDAQ.      المندق",
"SA.AL-NAMAS. النماص",
"SA.AL-QASSIM.القصيم",
"SA.ِAL-QUAIEIA.   القويعيه",
"SA.ِAL-QUNFUTHA.     القنفذه ",
"SA.AL-QURAYAT.  القريات",
"SA.AL-TAIF. الطايف",
"SA.AL-ZULFI. الزلفي",
"SA.ALARIDAH.   العارضه",
"SA.ALDARB.   الدرب",
"SA.ِALFARAA.   الفرعاء",
"SA.AlQUNFUTHA. القنفذه",
"SA.ALSHUBA.   الشعبه",
"SA.ALULA.  العلا",
"SA.ALWADIYAIN.  الواديين",
"SA.ARAR.عرعر",
"SA.BADEASHAMALI.  البدائع الشماليه",
"SA.BAHRA. بحره",
"SA.ِBAISH.     بيش",
"SA.BISHA.    بيشه",
"SA.ِBALJURASHY.  بالجرشي",
"SA.BURAYDAH.  بريده",
"SA.DAHARAN.   الظهران",
"SA.DAMMAM.الدمام",
"SA.DHARMA.  ضرما",
"SA.FARASAN.   فرسان",
"SA.HAFAR-BATIN.حفر الباطن",
"SA.HAIL. حايل",
"SA.HOTAT-BANITAMIM.حوطة بني تميم",
"SA.HURYMILA. حريملاء",
"SA.JAZAN.جازان",
"SA.JEDDAH.جده",
"SA.JUBAIL.الجبيل",
"SA.KHAMIS-MUSHAIT. خميس مشيط",
"SA.ِSHARORA.  شروره",
"SA.LAYLA. ليلا",
"SA.MAKKAH.مكه",
"SA.ِMAHAIL-ASEER.  محايل عسير",
"SA.MUDILEEF.  المظيليف",
"SA.NAJRAN.نجران",
"SA.ِRAFHA.    رفحاء",
"SA.RIYADH.الرياض",
"SA.SAJIR.   ساجر",
"SA.ِSABIA.   صبيا",
"SA.SKAKA.   سكاكا",
"SA.ِSURATOBIDAH.  سراة عبيدة",
"SA.SWAIDAN-ALAFLAJ.  سويدان الافلاج",
"SA.TABOUK. تبوك",
"SA.THURB.   ثرب",
"SA.TURAIF.   طريف",
"SA.UMLUJ.املج",
"SA.UNIZAH.   عنيزه",
"SA.WADI-ALDAWASER.وادي الدواسر",
"SA.YANBU.ينبع",



"----- INDONISIA ------------------------------",
"ID.JAKARTA.   جاكرتا",

"----- LIBYA ------------------------------",
"LY.MISRATA.    مصراته",
"LY.TRIPOLI.   طرابلس",
"LY.ZLITEN.    زليتن",
"LY.Emsaed.-",
"LY.Jalo.-",
"LY.Naloot.-",
"LY.Raslanof.-",
"LY.Shahat.-",
"LY.Tobrek.-",
"LY.Ubari.-",
"LY.Hoon.-",
"LY.Almarag.-",
"LY.BanyWalead.-",
"LY.Ekdames.-",
"LY.Benjuwad.-",
"LY.Benghazi.-",
"LY.Aljaghbub.-",
"LY.SERT.-",
"LY.ABARIQAH.-",
"LY.ALBAYDAA.-",
"LY.ALKAFRAH.-",
"LY.ALKHUMS.-",
"LY.ALZAWIAH.-",
"LY.AWJALH.-",
"LY.DARNAH.-",
"LY.DSRCH.-",
"LY.SABHA.-",





"----- ALGERIA ------------------------------",
"DZ.CONSTANTINE.    قسنطينه",


"----- JORDAN ------------------------------",
"JO.AMMAN. عمان",
"JO.KARAK. كرك",

"----- KUWAIT ------------------------------",
"KW.KUWAIT.  الكويت",

"----- EGYPT ------------------------------",
"EG.ZAGAZIG.الزقازيق‎",
"EG.DIKIRNIS. الدقهليه",
"EG.ASSUIT.   أسيوط",


"----- ETHIOPIA ---------------------------",
"ET.GOJJAM.قوجام",

"----- KENYA---------------------------",
"KE.NAIROBI.  كينيا",

"----- OMAN ------------------------------",
"OM.ALBRIMI.     البريمي",
"OM.EBRAA.   إبراء",
"OM.JEALAN_BOALI.    جعلان بوعلي",
"OM.JِAALAN_BOHASAN.  جعلان بو حسن",
"OM.MUSCAT.مسقط",
"OM.SUR.  صور",
"OM.BIDBID.  بدبد",
"OM.SUHUM.   صحم",
"OM.SAHAR.    صحار",
"OM.SALALA.  صلاله",
"OM.SWAIK.  سويق",
"OM.BARKA-Al Billa.  باركا البيلا",
"OM.ALRESTAG.   الرستاق",
"OM.LIWA.   لوى",
"OM.MASNAA.  مصنعة",
"OM.SAHAR.    صحار",

"----- TUNISIA ------------------------------",
"TN.HERAGLA.    هرقلة",


"----- YAMEN ------------------------------",
"YE.MUKALLA.المكلا",
"YE.TAIZ.  تعز",
"YE.QARYO.  قريو حضرموت",

"----- AUSTRALIA ------------------------------",
"AU.MELBOURNE.  ملبورن",


"---- DANMARK---------------------------------",
"DK.AARHUS.أرهوس",

"----- FRANCE ----------------------------",
"FR.ST-ETIENNE.FR42",
"FR.ST-ETIENNE-2.LOIRE",
"FR.LYON-BRON.FR69",
"FR.PROPRIANO.بروبريانو",
"FR.GRENOBLE.  FR  ",
"FR.FURIANI. FURIANI",


"---- NEW ZEALAND---------------------------------",
"NZ.AUCKLAND.أوكلاند",

"----SPAIN ---------------------------------",
"ES.BARCELONA. برشلونه ",
"ES.SOCUELLAMOS.SOC",
"ES.SANTHILARI.",
"ES.DURANGO.   ",

"----SVERIGE ---------------------------------",
"SV.Alingsas.",
"SV.Amal.",
"SV.Avesta.",
"SV.Bengtsfors.",
"SV.Boden.",
"SV.Bollnas.",
"SV.Boras.",
"SV.Borlange.",
"SV.Eksjo.",
"SV.Enkoping.",
"SV.Eskilstuna.",
"SV.Eslov.",
"SV.Falkenberg.",
"SV.Falkoping.",
"SV.Filipstad.",
"SV.Flen.",
"SV.Gavle.",
"SV.Gislaved.",
"SV.Gnosjo.",
"SV.GOTEBORG.",
"SV.Halmstad.",
"SV.Haparanda.",
"SV.Harnosand.",
"SV.Hassleholm.",
"SV.Helsingborg.",
"SV.Hogsby.",
"SV.Hudiksvall.",
"SV.Hultsfred.",
"SV.Jokkmokk.",
"SV.Jonkoping.",
"SV.Kalmar.",
"SV.Karlskoga.",
"SV.Karlskrona.",
"SV.Karlstad.",
"SV.Katrineholm.",
"SV.Kiruna.",
"SV.Koping.",
"SV.Kristianstad.",
"SV.Kristinehamn.",
"SV.Landskrona.",
"SV.Lessebo.",
"SV.Lidkoping.",
"SV.Linkoping.",
"SV.Ludvika.",
"SV.Lulea.",
"SV.Lund.",
"SV.Malmo.",
"SV.Mariestad.",
"SV.Marsta.",
"SV.Mellerud.",
"SV.Mjolby.",
"SV.Monsteras.",
"SV.Nassjo.",
"SV.Norrkoping.",
"SV.Norrtalje.",
"SV.Nybro.",
"SV.Nykoping.",
"SV.Orebro.",
"SV.Ornskoldsvik.",
"SV.Oskarshamn.",
"SV.Ostersund.",
"SV.Oxelosund.",
"SV.Pajala.",
"SV.Pitea.",
"SV.Ronneby.",
"SV.Sala.",
"SV.Savsjo.",
"SV.Simrishamn.",
"SV.Skara.",
"SV.Skelleftea.",
"SV.Skovde.",
"SV.Soderhamn.",
"SV.Sodertalje.",
"SV.Solleftea.",
"SV.Stockholm.",
"SV.Strangnas.",
"SV.Sundsvall.",
"SV.Tierp.",
"SV.Tranemo.",
"SV.Trelleborg.",
"SV.Trollhattan.",
"SV.Uddevalla.",
"SV.Ulricehamn.",
"SV.Umea.",
"SV.Uppsala.",
"SV.Vanersborg.",
"SV.Varberg.",
"SV.Varnamo.",
"SV.Vasteras.",
"SV.Vastervik.",
"SV.Vaxjo.",
"SV.Vetlanda.",
"SV.Visby.",
"SV.Ystad.",


"----UNITED KINGDOME ---------------------------------",
"UK.London.لندن",


"----USA ---------------------------------",
"US.HAMTRAMCK.  ",

"----GERMANY ---------------------------------",
"DE.PAPENBURG.    ",

"----Palestinian Territory---------------------------------",
"PS.HEBRON.      الخليل ",
"PS.Akka.        عكا ", 
"PS.Baysan.     بيسان", 
"PS.Beersheba.     بئر السبع", 
"PS.Bethlehem.    بيت لحم", 
"PS.DeirAalBalah.    دير البلح", 
"PS.Gaza.      غزه", 
"PS.Haifa.     حيفا", 
"PS.KhanYunis.  خان يونس",
"PS.Jaffa.    يافا", 
"PS.Jenin.    جنين", 
"PS.Jericho.    اريحا", 
"PS.Jerusalem.    القدس", 
"PS.Lod.     اللد", 
"PS.Nablus.     نابلس", 
"PS.Nazareth.   ألناصرة",
"PS.Qalqilya.    قلقيلية", 
"PS.Rafah.     رفح", 
"PS.Ramallah.     رام الله", 
"PS.Ramla.     الرملة", 
"PS.safad.     صفد",
"PS.Tayibe-KufurKassem.    كفر قاسم-الطيبة", 
"PS.Tiberias.     طبريا", 
"PS.Tulkarm.    طولكرم", 
"PS.Umm al-Fahm.    ام الفحم",

];














